services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api-rest-django
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=172.17.0.1
    network_mode: "host" 
